version: '2.2'

services:
    app:
        container_name: BuyWithStripe
        env_file:
            - .env
        build: .
        ports:
            - "8137:8000"
        restart: unless-stopped


