version: '2.12'

services:
    app:
        container_name: BuyWithStripe
        env_file:
            - .env
        build: .
        ports:
            - "8000:8000"
        restart: unless-stopped


