# Generated by Django 4.1.3 on 2022-11-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='СurrencyUSDRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
