# Generated by Django 4.1.3 on 2022-11-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_сurrencyusdrate_remove_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сurrencyusdrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
