# Generated by Django 4.1.3 on 2022-11-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_сurrencyusdrate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сurrencyusdrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
