# Generated by Django 4.1.3 on 2022-11-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_сurrencyusdrate_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сurrencyusdrate',
            options={'ordering': ('name',), 'verbose_name': 'Курс валюты', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterField(
            model_name='сurrencyusdrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс к USD'),
        ),
    ]
