# Generated by Django 4.1.3 on 2022-11-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_сurrencyusdrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.сurrencyusdrate', verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
