# Generated by Django 4.1.3 on 2022-11-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='items.сurrencyusdrate', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='сurrencyusdrate',
            name='rate',
            field=models.FloatField(verbose_name='Курс к USD'),
        ),
    ]
